import { Link } from "react-router-dom";
import { BarChart3, Bell, Car, FileText, LayoutDashboard, Plus, ShieldCheck, UserCog, Users, Wrench, type LucideIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cars, clients, maintenanceRows, reservations } from "@/data/rentalMock";

const nav: Array<[string, string, LucideIcon]> = [
  ["Dashboard", "/admin", LayoutDashboard], ["Cars", "/admin/cars", Car], ["Reservations", "/admin/reservations", Bell], ["Clients", "/admin/clients", Users], ["Managers", "/admin/managers", UserCog],
];

function AdminShell({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="min-h-screen bg-admin-panel text-primary-foreground"><div className="flex"><aside className="sticky top-0 hidden h-screen w-72 border-r border-primary-foreground/10 bg-primary/30 p-5 backdrop-blur-xl lg:block"><Link to="/" className="mb-8 flex items-center gap-3 font-display text-xl font-extrabold"><span className="grid size-10 place-items-center rounded-md bg-secondary text-secondary-foreground">TN</span>RouteRent CRM</Link><nav className="space-y-2">{nav.map(([label, href, Icon]) => <Link key={label} to={href} className="flex items-center gap-3 rounded-md px-3 py-3 text-sm font-bold text-primary-foreground/78 transition hover:bg-primary-foreground/10 hover:text-primary-foreground"><Icon className="size-4" />{label}</Link>)}</nav></aside><main className="min-w-0 flex-1 p-4 lg:p-8"><header className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="font-bold text-secondary">Admin / Manager</p><h1 className="text-4xl font-extrabold">{title}</h1></div><div className="flex gap-2"><Button asChild variant="admin"><Link to="/">Client site</Link></Button><Button variant="hero"><Plus className="size-4" />New</Button></div></header>{children}</main></div></div>;
}

function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <Card className={`border-primary-foreground/10 bg-surface-elevated/95 text-foreground shadow-card ${className}`}>{children}</Card>; }

export function AdminDashboard() {
  const stats = [["Total cars", cars.length, Car], ["Pending", 1, Bell], ["Clients", clients.length, Users], ["Revenue", "2.6k", BarChart3]];
  return <AdminShell title="Dashboard"><div className="grid gap-4 md:grid-cols-4">{stats.map(([label, value, Icon]) => <Panel key={label as string}><CardContent className="p-5"><Icon className="mb-4 size-6 text-primary" /><p className="text-sm font-bold text-muted-foreground">{label as string}</p><p className="font-display text-3xl font-extrabold">{value as string}</p></CardContent></Panel>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Panel><CardHeader><CardTitle>Recent requests</CardTitle></CardHeader><CardContent className="space-y-3">{reservations.map((r) => <div key={r.id} className="grid gap-2 rounded-md bg-surface p-4 md:grid-cols-[1fr_auto_auto] md:items-center"><div><p className="font-extrabold">{r.client}</p><p className="text-sm text-muted-foreground">{r.car} · {r.dates}</p></div><span className="font-bold text-primary">{r.total} TND</span><Button variant="premium" size="sm">Open</Button></div>)}</CardContent></Panel><Panel><CardHeader><CardTitle>Alerts</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-md bg-warning/20 p-4"><p className="font-extrabold">2 upcoming returns</p><p className="text-sm text-muted-foreground">Prepare inspection forms today.</p></div><div className="rounded-md bg-success/15 p-4"><p className="font-extrabold">WhatsApp queue ready</p><p className="text-sm text-muted-foreground">3 messages waiting for confirmation.</p></div></CardContent></Panel></div></AdminShell>;
}

export function AdminCars() { return <AdminShell title="Car management"><Panel><CardHeader><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><CardTitle>Fleet</CardTitle><Input className="max-w-sm" placeholder="Search matricule, brand..." /></div></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="text-left text-muted-foreground"><tr><th className="p-3">Car</th><th>Type</th><th>Fuel</th><th>Km</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>{cars.map((c) => <tr key={c.id} className="border-t border-border"><td className="p-3 font-extrabold">{c.brand} {c.model}<p className="text-xs font-medium text-muted-foreground">{c.matricule}</p></td><td>{c.type}</td><td>{c.fuel}</td><td>{c.mileage.toLocaleString()}</td><td>{c.pricePerDay} TND</td><td><span className={`rounded-md px-2 py-1 font-bold ${c.isAvailable ? "bg-success text-success-foreground" : "bg-muted text-muted-foreground"}`}>{c.isAvailable ? "Available" : "Booked"}</span></td><td><Button asChild variant="ghost" size="sm"><Link to={`/admin/cars/${c.id}/maintenance`}>Edit</Link></Button></td></tr>)}</tbody></table></CardContent></Panel></AdminShell>; }

export function MaintenancePage() { return <AdminShell title="Fiche entretien"><Panel><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><Wrench className="size-5 text-primary" />Renault Clio 5</CardTitle><Button variant="hero">Export Excel</Button></div></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-muted-foreground"><tr>{["Date", "Type", "Km", "Next", "Cost", "Provider", "Notes", ""].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{maintenanceRows.map((row) => <tr key={row.date} className="border-t border-border">{Object.values(row).map((v) => <td key={v} className="p-3"><Input defaultValue={v} /></td>)}<td><Button variant="ghost" size="sm">Delete</Button></td></tr>)}</tbody></table><Button variant="premium" className="mt-4"><Plus className="size-4" />Add row</Button></CardContent></Panel></AdminShell>; }

export function AdminReservations() { return <AdminShell title="Reservations"><Panel><CardHeader><CardTitle>Lifecycle management</CardTitle></CardHeader><CardContent className="space-y-3">{reservations.map((r) => <div key={r.id} className="grid gap-3 rounded-md border border-border bg-surface p-4 lg:grid-cols-[1fr_1fr_auto] lg:items-center"><div><p className="font-extrabold">{r.id} · {r.client}</p><p className="text-sm text-muted-foreground">{r.phone}</p></div><div><p className="font-bold">{r.car}</p><p className="text-sm text-muted-foreground">{r.dates} · {r.total} TND</p></div><div className="flex gap-2"><Button variant="premium" size="sm">Accept</Button><Button variant="outline" size="sm">Reject</Button><Button asChild variant="ghost" size="sm"><Link to="/admin/reservations/RS-1048">Contract</Link></Button></div></div>)}</CardContent></Panel></AdminShell>; }

export function ContractPage() { return <AdminShell title="Contrat de location"><div className="grid gap-6 lg:grid-cols-[1fr_0.85fr]"><Panel><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="size-5 text-primary" />Manual fields</CardTitle></CardHeader><CardContent className="grid gap-4"><Input placeholder="État de la carrosserie" /><Input placeholder="Niveau de carburant au départ" /><Input placeholder="Kilométrage au départ" /><Input placeholder="Caution / Dépôt" /><Input placeholder="Remarques générales" /><Button variant="hero" size="xl">Generate PDF</Button></CardContent></Panel><Panel><CardHeader><CardTitle>Auto-filled summary</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><b>Client:</b> Amira Ben Youssef · CIN 08456231</p><p><b>Car:</b> Renault Clio 5 · 214 TN 7821</p><p><b>Dates:</b> 24 Apr → 29 Apr</p><p><b>Total:</b> 625 TND</p><div className="rounded-md bg-metal p-5 text-center"><ShieldCheck className="mx-auto mb-3 size-10 text-primary" /><p className="font-extrabold">Printable contract preview</p></div></CardContent></Panel></div></AdminShell>; }

export function AdminClients() { return <AdminShell title="Client management"><Panel><CardHeader><CardTitle>Registered clients</CardTitle></CardHeader><CardContent className="space-y-3">{clients.map((c) => <div key={c.id} className="grid gap-3 rounded-md bg-surface p-4 md:grid-cols-[1fr_1fr_auto] md:items-center"><div><p className="font-extrabold">{c.name}</p><p className="text-sm text-muted-foreground">CIN {c.cin}</p></div><div><p>{c.email}</p><p className="text-sm text-muted-foreground">{c.phone}</p></div><Button variant="ghost" size="sm">History ({c.reservations})</Button></div>)}</CardContent></Panel></AdminShell>; }

export function AdminManagers() { return <AdminShell title="Manager management"><div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><Panel><CardHeader><CardTitle>Add manager</CardTitle></CardHeader><CardContent className="grid gap-4"><Input placeholder="Name" /><Input placeholder="Email" /><Input placeholder="Temporary password" type="password" /><Button variant="hero">Invite manager</Button></CardContent></Panel><Panel><CardHeader><CardTitle>Managers</CardTitle></CardHeader><CardContent className="space-y-3">{["Mouna Rekik", "Karim Saidi"].map((name) => <div key={name} className="flex items-center justify-between rounded-md bg-surface p-4"><span className="font-extrabold">{name}</span><Button variant="outline" size="sm">Remove</Button></div>)}</CardContent></Panel></div></AdminShell>; }
